### ISSUE TITLE
Release for Firefox

### ISSUE THREAD

**Issue by esphen** [socialtables/chrome-prettier#6]
Hi!

I just wanted to drop in and say that this extension works without any modifications in Firefox. It would be awesome if you could release it there as well!

All you need to do to prepare the archive is to install web-ext and run web-ext build in the dist directory.

I made an npm script which makes this really easy over at PR #5. All you need to do is to run `npm run build:firefox` to build the release archive which can be uploaded to https://addons.mozilla.org.

**Comment by conorhastings** [comment]
https://addons.mozilla.org/en-US/firefox/addon/prettier/

**Comment by eliihen** [comment]
Awesome! 🎉
